[build] 
  publish = "dist"
  command = "npm run build"

[[plugins]]
  package = "./node_modules/@netlify/demo-restaurant-sites-data/plugins/contentful"

  [plugins.inputs]
    # Directory for the generated JSON data files to reside in
    dataDir = "public/data"
